mozilla/dinobuildr

config.py

The `script_path` variable was a holdover from a previous design concept for this script and it was getting in the way of our ability to `curl` this script to a machine without writing the script to a file.

Removing the defunct script_path variable.

---

config.py
manifest.json
repo/macos-versioncheck.sh

Dinobuildr will now read exit codes when executing shell scripts and will terminate the build if the exit code 1 is returned by the script. This is useful for error handling and should be expanded in the future to accept other error codes.
We've also added a minimum OS check, to make sure that the build is being executed on the minimum version of the operating system. The build will fail if the minimum version is not present.

Feature: Operating System Check / Exit Codes for Shell Scripts

---

config.py
manifest.json
repo/crashplan-postinstall.sh

On certain machines, the Crashplan postinstall script would complain that it couldn't find the Crashplan process and the build would fail. 
```
Executing: Crashplan PostInstall
*** Waiting for Crashplan to launch and then quitting it...
*** No matching processes were found
```
As a hack, we put an `exit 0` in the script so the whole build wouldn't fail in this case.

Bug: Crashplan Postinstall Script would fail occasionally

---

config.py
manifest.json
repo/macos-versioncheck.sh

Set the minimum accepted macOS version to 10.13.0, since our update script will push out minor versions and we only want to halt the build if it's running on a machine that isn't on High Sierra.

Bug: Roll back macOS version check to 10.13.0

---

config.py
manifest.json
repo/set-computername.sh

Per #51 - Hostname is a bit of a misnomer, since we're not actually setting the hostname anywhere. A more accurate feature description would be "Set ComputerName and LocalHostName" but that's annoying. 
We added the set-computername.sh script early in the build so that software like Crashplan will have access to the correct hostname, in case it matters. 
Build has been tested in a development branch, ready to push to master.

Feature: Set "Hostname"

---

config.py

Shell scripts were missing a newline after executing, which was causing the script output to be REAL ugly. Also added a little messaging around script start and the manifest hash check to make it make a little more sense.

Bug: Add missing newlines after shell script executions

---

config.py
dinobuildr.sh

Previously, running dinobuildr against a specific branch required changing the `branch` variable in `config.py`, which was annoying. This PR adds support for "arbitrary" branches within the repo and org `config.py` is configured to use. 
This is particularly useful in testing, since a dinobuildr can be used to test arbitrary branches without needing to pull the branch down, change the variable and push back to the development branch (then undo all those changes when the testing is complete).

Feature: Arbitrary branch support

---

config.py
dinobuildr.sh

Let's try this again (since I messed it up last time) (see #90 and #91)
Previously, running dinobuildr against a specific branch required changing the branch variable in config.py, which was annoying. This PR adds support for "arbitrary" branches within the repo and org config.py is configured to use.
This is particularly useful in testing, since a dinobuildr can be used to test arbitrary branches without needing to pull the branch down, change the variable and push back to the development branch (then undo all those changes when the testing is complete).

Arbitrary Branch Support

---

ambient_manifest.json
config.py
repo/corsica/disable-bluetooth-setup-assistant.sh
repo/corsica/launch-firefox.sh

Disables Bluetooth Setup Assistant at startup if no keyboard, mouse, or trackpad is detected.

Feat disable bluetooth assistance

---

ambient_manifest.json
config.py
repo/corsica/launch-firefox.sh

Added LaunchDaemon to clear the Firefox sessionstore and disable automatic open app restores after a reboot or shutdown

Keep Firefox fullscreen after shutdown or reboot

---

ambient_manifest.json
config.py
manifest.json
repo/corsica/auto-update.sh

This feature allows the corsica displays to aggressively autoupdate. They will check Apple for OS updates on the 1st and 15th of every month at 3am local time, and will reboot whether there are updates or not. Firefox is set to autoupdate on launch, so any Firefox updates will be installed at that time.
Devices can be put into a "canary" mode to check for updates every night at 3am. These devices should get updates before the rest of the fleet, so if they break we can interrupt the update process on the rest of our fleet with our Informant service.

Feature - Corsica Autoupdate

---

config.py
manifest.json
repo/crashplan-postinstall.sh
repo/custom.properties
repo/macos-versioncheck.sh
repo/userInfo.sh

Making Mojave work with Dinobuildr was a little tricker than anticipated, but mostly because we had taken some shortcuts and had a few bugs in some scripts. Here's the important stuff
It's now harder to set the wallpaper in Mojave without using Configuration Profiles, because any calls to `osascript` need to be authorized by the user, regardless of if `osascript` was called with `sudo` or not. This is actually a good change, as it means that less sketchy stuff can be done with `osascript`, but it means that there is a prompt that you have to click through in our build. I moved this step to right after the OS version check to make it easy to get out of the way quickly. 
Apple added a feature where apps that you launch magically appear in the dock in a separate section, and stick around …

Mojave Support

---

ambient_manifest.json
config.py
manifest.json
repo/disable-guest.sh
repo/dock-config.sh
repo/wallpaper.sh

This is a two-features for the price of one type of deal. 
After Mojave, setting the desktop wallpaper became more complicated, as using the old tried and true [applescript method](https://github.com/mozilla/dinobuildr/blob/1ab397d9bc27ea538ab56a5a9c817a372d4f0aae/repo/wallpaper.sh) resulted in a TCC prompt. 
We solve for this by using [Steve Ward's method](https://github.com/tech-otaku/macos-desktop) for setting the desktop wallpaper the "proper way" in Mojave using a shell script. We curl down a commit-pinned version of this script and execute it. 
We also are disabling the Guest Login feature of macOS. With Filevault enabled, the Guest account only has access to Safari and the disk is still encrypted, but since this isn't a feature most people will likely use we're turning it off.

Disable Guest Account and set the wallpaper via a different method

---

dino_engine.py
production_manifest.json
resources/dock-config.sh
resources/firefox-bookmarks.sh
resources/set-computername.sh

Switching out the old Vidyo bookmark to sso.mozilla.com
This started as a basic update but ended up spiraling into bigger changes. 
Apparently this never got done and we hadn't previously needed it. We supported `pkgs` in LFS, but not `pkgs` pulled down from the internet. 
This apparently had been broken all along. The fix is a little hacky, but time pressure. We'll now exit on installation errors. 
https://github.com/mozilla/dinobuildr/blob/1f48dfe2403f72564d471ca149ec5a2fae5b5fe5/resources/set-computername.sh#L30
You need all three!
Spring cleaning! Pass one, waiting on more input from the service desk team
removed old Vidyo app, added Zoom instead, updated Dock

Update firefox-bookmarks.sh, add Zoom, remove Vidyo

---

resources/corsica/firefox-settings.sh

Reverts mozilla/dinobuildr#162
I haven't had a chance to test this yet but this won't likely run without updating the file hashes in the manifests (and the manifest hashes in the dino_engine.py). Suggest making those changes and retesting.

Revert "Allow video autoplay on Corsica screens"

---

dino_engine.py
dinobuildr.sh

Adding support for external Github repos so folks from the community can PR changes and we can _actually test them_. 
This change adds the following optional flags to the `dinobuildr.sh`and `dino_engine.py` scripts: 
```
-r, --repo
The name of the target Github repository (defaults to dinobuildr)
-o, --org
The name of the target Github org (defaults to Mozilla)
```
Example usage: 
`sudo dinobuildr.sh -o luciusbono -r dinofork -b my-cool-test-branch`
This runs dinobuildr against branch called `my-cool-test-branch` in the `dinofork` repository in the `luciusbono` Github org.

External Repo Support

---

ambient_display_manifest.json
dino_engine.py
resources/corsica/firefox-settings.sh

This was originally proposed (and implemented) by @mythmon in https://github.com/mozilla/dinobuildr/commit/57032b3d004be5f05877c834a09e3aac9664c852 but we had to back out the change (for other reasons) and my weak git-fu screwed everything up. 
This disables the auto-play blocking functionality in our ambient display boards, since we want things to automatically play.

Allowing autoplay media to play by default, as this is a change in FF68

---

dino_engine.py

It’s unnecessary to copy the pkg file to the local_dir since we are executing the pkg file directly from the mounted dmg file.

Removed lines in dmg_install function

---

dino_engine.py

Per https://bugzilla.mozilla.org/show_bug.cgi?id=1592852#c18, a bug was identified in the DMG processor, causing .app installers to be copied into the Applications directory without recursively changing ownership of all the files in the .app bundle to the logged in user. Since we run dinobuildr with sudo, any file in the .app bundle was owned by root - which causes the Firefox updater to prompt the user instead of silently installing updates, which is not ideal. 
We also stop changing the permissions on files in the .app installer, since this should not be required. Finally, we set the group ownership of anything installed inside the.app installer to `admin` since the user is likely going to be in the admin group. This isn't a great assumption, and in a perfect world we would determine if …

Fixing .app installer bug in DMG processor and removing hash checks for the manifest file

---

dino_engine.py

missed this the first time I submitted the PR 180. The wallpaper-catalina branch still needs the manifest hash to match the file hash!

update manifest hash!

---

dino_engine.py
production_manifest.json
resources/firefox-bookmarks.sh

Riot Matrix has replaced IRC Cloud as Mozilla's public messaging platform, so I've updated firefox-bookmarks.sh to reflect that. The hash has been updated in production_manifest.json (commit [3e1489a](https://github.com/mozilla/dinobuildr/commit/3e1489ae3b38431e3aa745d80c2297a57bef9d8e)) and in firefox-bookmarks.sh (commit [8613269](https://github.com/mozilla/dinobuildr/commit/86132698e0608984f2b5c167c6fe53019ba95eea))

Add Matrix bookmark to /resources/firefox-bookmarks.sh in branch:wallpaper-catalina

---

production_manifest.json

update Crashplan to 8.0.0, use direct download link (from our internal documentation); update file hash for dmg installer
This time I tested on virtualbox vm (10.15.5) and a freshly erased/reinstalled macbook pro 16" and checks out fine/works with install.
Thanks!

update Crashplan to 8.0.0

---

production_manifest.json

update zoom to more recent version.
I ran the change by freshness in AVops and freshness agrees with updating zoom in our images to a recent zoom (5.1.2, 5.1.28648.0705 being the latest one)
tested in a virtualbox vm (10.15.5) and on a macbook pro 16" (10.15.6), installed cleanly and able to start zoom calls.

update zoom to 5.1.2

---

dino_engine.py
production_manifest.json

Patch cowritten by @geraltofpython and @jlin that implements a new hash type "autohash-firefox" that allows the use of a "latest" version tag in the production manifest for Firefox in order to automatically hash against current version hashes provided by Mozilla.
This tracks dinobuildr to the current Firefox release without having to rehash manually.
Tested in Virtualbox with 10.15.5 and on a MBP16" with 10.15.6
Appreciate lots of testing before merging!

feature autohash-firefox - implements #184

---

dino_engine.py

SHA256SUMS file no longer uses b'' form for hashes in FX80. Minor fixup in our autohash_firefox_find_hash() function to be able to interpret the sums.
Tested on 10.15.5 VM and 10.15.6 on MacBook Pro 13" 2016.
This fixes Issue #193

update autohash to work with fx80 format

---

production_manifest.json

Reverts mozilla/dinobuildr#197
found an issue with unable to update zoom after installation with this version, backing this out for now.

Revert "updated zoom to 5.3.0 version"

---

production_manifest.json
resources/macos-versioncheck.sh
resources/update-macos.sh
resources/wallpaper.sh

Merging in initial Big Sur compatibility for Intel based macs
Tested on MacBook Pro 15" 2015 running Big Sur 11.2 beta
Tested on VirtualBox VM running Catalina 10.15.7
Tested on M1 Macbook Air running 11.1 (not optimized, still installing Intel binaries)
All the programs installed still need Rosetta on the M1 mac, will need to update this in a future release, but for now, at least Dinobuildr runs on Big Sur and installs all updated software
brief summary of changes:
versioncheck - set minimum to 10.15, allow 11
wallpaper - merged in updates from upstream, temporarily using scripts from jlin's repo - will update in future
softwareupdate - remove deprecated suspend-background option.

Merge Bigsur Compatability

---

production_manifest.json
resources/install-rosetta2.sh

Check for arm (via uname -p) and install rosetta 2 if found
Tested on M1 - rosetta installed as it should
Tested on Intel Mac Big Sur - no op as expected
Tested on Intel VM Catalina - no op as expected
refined the messaging a bit so it's clear that there's a test, and rosetta installation is depending on the platform

Upd8 m1 rosetta2

---

production_manifest.json
resources/wallpaper.sh

Merging in an update to modify the background image version check - previously it was too narrow (was checking minor versions, so 11.0.1 would trip the check for 11.0 and breaking out of the script)
tested on a macbook pro running 11.1

Upd8 background image version check

---

production_manifest.json

update zoom to 5.6.7 1020
tested on a loaner mac running Big Sur 11.5 beta

update zoom to 5.6.7 1020

---

production_manifest.json

Reverts mozilla/dinobuildr#210
revert due to an issue jdirx found when trying to run dinobuildr.

Revert "update zoom to 5.6.7 1020"

---

production_manifest.json

update to Slack Universal binary 4.17.0
tested in 
Catalina VM
Physical laptop Big Sur 11.5 beta
the universal binary works in catalina and would make setting up the M1 computers easier.

update to Slack Universal binary 4.17.0

---

production_manifest.json

update zoom to 5.7.1
Tested on 
physical mac laptop Big Sur 11.5 beta
Catalina VM

update zoom 5.7.1

---

production_manifest.json

update slack to 4.21.1
tested on VM running Big Sur. This is a series of updates to get all apps updated in order to merge in the Monterey compatibility patch

update slack to 4.21.1

---

production_manifest.json

Bump version of code42 to 8.8.1 build 36
tested working with
- Macbook Air running Monterey
- VM running Big Sur
Installs cleanly and runs.

version bump code42 8.8.1.36

---

production_manifest.json

bump slack to 4.23.0
tested on
- macbook air running Monterey
- vm running Big Sur

version bump Slack 4.23.0

---

production_manifest.json

We weren't using very much of the deploy.properties and it was interfering with code42 app startup.

remove code42 deploy properties

---

production_manifest.json

update code42 to 8.8.2 build 143
tested with a loaner MacBook air 2020 with monterey

update code42 to 8.8.2 build 143

---

production_manifest.json

We should move the macos update step either to outside (so the tech can take care of it) - or perhaps make the script smarter when validating whether an update is needed. For now, this step causes a long delay when downloading macos updates that can be up to few gigabytes in size, and when apple servers time out, this breaks the rest of the build.

remove macos update phase
