- config.py
- create_manifest.py
- manifest.json
- repo/crashplan-postinstall.sh
Replaced osascript with killall. CrashPlan now quits nicely after installation.
> Bug crashplan timeout

- README.md
> MacOS > macOS

- config.py
- manifest.json
- repo/restart-computer.sh
- repo/update-macos.sh
Since updates are going to occasionally require updates, we're going to force a restart at the end of the build for consistency. 
We also had to add ANOTHER update check since the IAmRoot patch seems to block the 10.13.2 update if it's not present, which is weird.
> Feature: Restart at the end of the build

- config.py
- create_manifest.py
- manifest.json
Updating Firefox in our build to 58b11 and tweaking some titles for things in the manifest.
> Update Firefox to 58b11

- config.py
- manifest.json
- repo/dock-config.sh
Per: #66 this PR adds Downloads back to the dock.
This PR has been tested against a development branch.
> Feature: Add Downloads folder to dock. 

- config.py
I managed to botch a merge conflict and I specified the wrong hash. Tested changes on my virtual machine.
> Hotfix: Bad Manifest Hash

- config.py
- manifest.json
- repo/app-store-updates.sh
- repo/screen-saver.sh
Issue #73: enabled automatic updates for macOS and apps from the App Store.
> Feat app store updates

- config.py
- manifest.json
- repo/update-macos.sh
Added the `--suspend-background` flag to `softwareupdate` to improve reliability.
> Bug: Suspend Background Updates

- config.py
- manifest.json
- repo/screensaver.sh
Feature: Configure screen saver start time #62
> Feat screensaver

- config.py
- manifest.json
- repo/firewall.sh
Removed extra sudo from the firewall script.
> Feat firewall

- config.py
- manifest.json
- repo/.gitattributes
- repo/dino-wallpaper.png
- repo/wallpaper.jpg
- repo/wallpaper.sh
Changed wallpaper and updated the wallpaper script.
> Feat wallpaper

- config.py
- manifest.json
- repo/firefox-bookmarks.sh
- repo/firefox-profile.pkg
Use distribution.ini to configure bookmarks instead of importing the Firefox profile.
> Feat firefox bookmarks

- config.py
- manifest.json
Updating the Vidyo Desktop version to 3.6.14
> Vidyo Desktop Update to 3.6.14

- config.py
- manifest.json
- repo/macos-versioncheck.sh
Set minimum macOS version to 10.13.3
> Feat macos versioncheck

- config.py
- dinobuildr.sh
Even though I tested this yesterday, running it again post-merge is erroring out. Looks like `dinobuildr.sh` is not passing the branch argument to `config.py` properly.
> Revert "Feature: Arbitrary branch support"

- config.py
Due to @luciusbono failing at git, my last PR broke everything.
> Re-adding argeparse which seems to have falled out of my last commit

- config.py
- manifest.json
> Feat firefox

- config.py
- manifest.json
> Updating Firefox to 59.

- config.py
- manifest.json
- repo/firefox-bookmarks.sh
> Import Firefox bookmarks using policy engine.

- README.md
- ambient_manifest.json
- config.py
- repo/corsica/skip-data-privacy-setup.mobileconfig
- repo/corsica/skip-icloud-setup.mobileconfig
- repo/corsica/skip-siri-setup.mobileconfig
Added support for configuration profiles.
> Feat mobileconfig

- config.py
- manifest.json
Download latest Firefox release build, 60.0.2
> Updated manifest to download Firefox 60.0.2

- ambient_manifest.json
- config.py
- repo/corsica/prompt-computername.sh
- repo/corsica/set-computername.sh
Added a GUI popup for hostname because we won't know what the corsica endpoints will be named until build time (usually)
> Prompt for hostname in the Corsica build

- config.py
- manifest.json
Firefox 62.0.2 is the latest version of Firefox and so we like it the most.
> Updating Firefox to 6.0.2

- ambient_manifest.json
- config.py
- manifest.json
Main macOS build: Firefox 63.03
Corsica build: Firefox ESR 60.3.0
> Update Firefox to the latest version in our builds

- dino_engine.py
- production_manifest.json
> updated firefox to 65.0.2

- dino_engine.py
- production_manifest.json
Updating to crashplan 6.9.2 as it was causing weird stalls while upgrading
> updating crashplan to 6.9.2

- resources/corsica/firefox-settings.sh
This fixes issues with Youtube and other video Embeds not playing on Corsica.
> Allow video autoplay on Corsica screens

- dino_engine.py
- production_manifest.json
> Updating Zoom and FF

- ambient_display_manifest.json
- dino_engine.py
- resources/corsica/firefox-settings.sh
Ambient display build was broken (wrong hash for the firefox-settings.sh script). Updated script (and hashes) to include a line that removes a prompt when quitting Firefox asking the user to preserve tabs. Also updated FF ESR to 68.
> Fix corsica build

- dino_engine.py
My goal is to improve the readability in dino_engine.py. 
Changes so far:
- Created a main function.
- Moved all of the fun stuff into the main function.
- Deleted all global variables.
- Fixed the downloader function to account for the deleted global variables.
> Feat main function

- dino_engine.py
- production_manifest.json
Should have gotten this done last week, but was out sick half the week.
> Update Crashplan to 7.0.0

- dino_engine.py
- production_manifest.json
- resources/dock-config.sh
- resources/firefox-bookmarks.sh
Switching phonebook.moz to people.moz. Finally adding in Slack, and updating Firefox to 68.0.1
> updating bookmarks, adding slack, updating Firefox

- dino_engine.py
- production_manifest.json
- resources/wallpaper.sh
Making a change to the curl command used in the wallpaper script for possible Catalina compatibility.
> Changing curl command to hopefully work with macOS Catalina

- production_manifest.json
- resources/dock-config.sh
I am doing a "manual rebase" for lack of a better term of patch #179 into the wallpaper-catalina branch for issue #178
The wallpaper-catalina branch has diverged from master and I can't be confident in just doing a merge or a rebase. 
The wallpaper-catalina is our interim solution to the wallpaper issue, but we will be overhauling this mechanism in our future issues/PR's, this current pull request is to take care of a papercut issue that is bugging us during everyday use of the wallpaper-catalina branch.
> Fix dock catalina in wallpaper brach

- production_manifest.json
- resources/dock-config.sh
- resources/firefox-bookmarks.sh
- resources/wallpaper.sh
Hi Lucius! 
I finally did the rebase of Wallpaper-catalina branch to master, with existing and minor fixes from the last month. This pull request is to merge the changes in wallpaper-catalina back into master.
After this is merge, we can finally start to use master to develop future changes!
This doesn't change the existing wallpaper script, just a rebase for merging into master.
I tested on a virtualbox vm and a mbp 16.
Thanks very much
> rebase and merge Wallpaper catalina

- production_manifest.json
- resources/wallpaper-firefox.png
- resources/wallpaper.jpg
- resources/wallpaper.sh
Worked with @jlin, @missterclean , @geraltofpython, @dirxforce to update background image. This is now the current logo w/ current branding. 
Tested on VM & Mbp 16-inch
> update background image

- production_manifest.json
Updated Slack version to 4.8.0 and changed the hash
> Updating Slack hash

- production_manifest.json
- resources/dock-config.sh
Update a few apps in our manifest
code42 8.5.0 and dock application link
slack 4.12.0
zoom 5.4.59780.1220
changed order of install around so zoom isn't stealing focus
> Upd8 manifest

- production_manifest.json
update to code42 8.6.1
tested in
Catalina VM 
Big Sur VM 11.3
Big Sur physical test laptop on 11.5 beta
> update to code42 8.6.1

- production_manifest.json
- resources/firefox-bookmarks.sh
> change bookmark to go to JSM

- production_manifest.json
update to code42 8.8.1
tested on
- MacBook Air running Big Sur
- MacBook Air running Monterey
- VM running Monterey
> update to code42 8.8.1

- production_manifest.json
as per https://github.com/mozilla/dinobuildr/issues/228
> remove code42 as per issue 228

- resources/firefox-bookmarks.sh
remove bookmarks as per issue #229 
implements #229
> remove all bookmarks except sso

- production_manifest.json
- resources/firefox-bookmarks.sh
update firefox-bookmarks.sh hash
> Upd8 pare down bookmarks

- production_manifest.json
- resources/dock-config.sh
update dock for removing the code42 icon - completion of #228
> update dock for removing code42

- production_manifest.json
> update to Zoom 5.10.1.5839
